name: linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.16'
          - '5.18'
          - '5.20'
          - '5.22'
          - '5.30'
    container:
      image: perl:${{ matrix.perl-version }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_INITDB_ARGS: --auth-host=md5
    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Fix ExtUtils::MakeMaker (for Perl 5.16 and 5.18)
        run: cpanm -n App::cpanminus ExtUtils::MakeMaker
      - name: Install dependencies
        run: |
          cpanm -n --installdeps .
          cpanm -n Mojo::Pg
      - name: Run tests
        env:
          TEST_ONLINE: postgresql://postgres:postgres@postgres:5432/postgres
        run: prove -l t
